# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

addRowWiseC <- function(WeightVectors, DataPoint) {
    .Call('GeneralizedUmatrix_addRowWiseC', PACKAGE = 'GeneralizedUmatrix', WeightVectors, DataPoint)
}

Delta3DWeightsC <- function(vx, Datasample) {
    .Call('GeneralizedUmatrix_Delta3DWeightsC', PACKAGE = 'GeneralizedUmatrix', vx, Datasample)
}

trainstepC <- function(vx, vy, DataSampled, BMUsampled, Lines, Columns, Radius, toroid) {
    .Call('GeneralizedUmatrix_trainstepC', PACKAGE = 'GeneralizedUmatrix', vx, vy, DataSampled, BMUsampled, Lines, Columns, Radius, toroid)
}

